### ISSUE TITLE
java.security.InvalidKeyException: can't identify EC private key.

### ISSUE THREAD

**Issue by iScript** [ofdrw/ofdrw#166]
传入自己的p12文件，报这个错，该如何解决。

java.security.InvalidKeyException: can't identify EC private key.

	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(ECUtil.java:287)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.GMSignatureSpi.engineInitSign(Unknown Source)
	at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1371)
	at java.base/java.security.Signature.initSign(Signature.java:636)
	at org.ofdrw.sign.signContainer.SESV4Container.sign(SESV4Container.java:144)

	at

**Comment by Trisia** [comment]
该问题不属于OFDRW库问题。
