### ISSUE TITLE
在macpro（m1)环境下运行 QuickStart时报错。是不是字体资源的问题。2.0.3版本

### ISSUE THREAD

**Issue by Hz1234** [ofdrw/ofdrw#188]
错误信息如下所示：
Exception in thread "main" java.lang.NullPointerException
at org.ofdrw.font.EnvFont.strBounds(EnvFont.java:83)
at org.ofdrw.layout.element.TxtGlyph.getW(TxtGlyph.java:49)
at org.ofdrw.layout.element.Span.blockSize(Span.java:293)
at org.ofdrw.layout.element.Paragraph.doPrepare(Paragraph.java:487)
at org.ofdrw.layout.engine.Segment.tryAdd(Segment.java:86)
at org.ofdrw.layout.engine.SegmentationEngine.process(SegmentationEngine.java:51)
at org.ofdrw.layout.OFDDoc.close(OFDDoc.java:596)
at com.example.ofdrelation.ofdrw.HelloWorld.main(HelloWorld.java:24)

**Comment by Trisia** [comment]
该问题是缺少字体导致，该问题将会于下个版本修复。

在无法找到字体使用默认字体替换，如宋体或衬线

**Comment by Trisia** [comment]
2.0.4 修复
