### ISSUE TITLE
旧版foxit转换的文件发生zip解压问题

### ISSUE THREAD

**Issue by WhisperwindBill** [ofdrw/ofdrw#190]
[文档2.zip](https://github.com/ofdrw/ofdrw/files/11131699/2.zip)
java.util.zip.ZipException: invalid entry compressed size (expected 402 but got 398 bytes)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:389) ~[na:1.8.0_362]
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196) ~[na:1.8.0_362]
	at org.ofdrw.reader.ZipUtil.unZipFiles(ZipUtil.java:86) ~[ofdrw-reader-2.0.3.jar:na]
	at org.ofdrw.reader.OFDReader.<init>(OFDReader.java:137) ~[ofdrw-reader-2.0.3.jar:na]

**Comment by WhisperwindBill** [comment]
运行环境为java8_362

**Comment by Trisia** [comment]
在2.0.5 版本中并未出现该问题，请升级版本。

**Comment by WhisperwindBill** [comment]
额，这个问题确实发生在2.0.5版本上，在使用HTMLExporter时发生，环境为windows+tomcat，JDK8下；
测试代码如下：
ByteArrayOutputStream byteArrayOutputStream=new ByteArrayOutputStream();
 HTMLExporter exporter=new HTMLExporter(stream,byteArrayOutputStream);
        exporter.export();
stream来自MultipartFile.getInputStream()
