### ISSUE TITLE
获取字体库的兼容性问题

### ISSUE THREAD

**Issue by sunjjj013** [ofdrw/ofdrw#196]
在ofd转pdf的问题：
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.ofdrw.converter.FontLoader.loadAsDefaultFont(FontLoader.java:217)
	at org.ofdrw.converter.FontLoader.init(FontLoader.java:189)
	at org.ofdrw.converter.FontLoader.syncInit(FontLoader.java:91)
	at org.ofdrw.converter.FontLoader.getInstance(FontLoader.java:132)
	at org.ofdrw.converter.ItextMaker.getFont(ItextMaker.java:774)
	at org.ofdrw.converter.ItextMaker.writeText(ItextMaker.java:690)
	at org.ofdrw.converter.ItextMaker.writePageBlock(ItextMaker.java:316)
	at org.ofdrw.converter.ItextMaker.writePageBlock(ItextMaker.java:334)
	at org.ofdrw.converter.ItextMaker.writeLayer(ItextMaker.java:217)
	at org.ofdrw.converter.ItextMaker.makePage(ItextMaker.java:121)
	at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:87)
	... 2 more

原因是获取字体的名字是汉字，但是我本地mac系统的字体库都是拼音。希望可以兼容拼音

**Comment by Trisia** [comment]
你可以使用

**Comment by sunjjj013** [comment]
public void init() {
        if (OSinfo.isWindows()) {
            scanFontDir(new File(DEFAULT_FONT_DIR_WINDOWS));
            // 扫描用户字体目录
            String username = System.getProperties().getProperty("user.name");
            scanFontDir(new File(String.format("C:\\Users\\%s\\AppData\\Local\\Microsoft\\Windows\\Fonts", username)));
        } else if (OSinfo.isMacOS()) {
            scanFontDir(new File(DEFAULT_FONT_DIR_MAC));
        } else if (OSinfo.isMacOSX()) {
            scanFontDir(new File(DEFAULT_FONT_DIR_MAC));
        } else if (OSinfo.isLinux()) {
            scanFontDir(new File(DEFAULT_FONT_DIR_LINUX));
        }

        addAliasMapping("小标宋体", "方正小标宋简体");
        addAliasMapping("KaiTi_GB2312", "楷体");
        addAliasMapping("楷体", "KaiTi");
        addAliasMapping("宋体", "SimSun");

        addSimilarFontReplaceRegexMapping(".*Kai.*", "楷体");
        addSimilarFontReplaceRegexMapping(".*Kai.*", "楷体");
        addSimilarFontReplaceRegexMapping(".*MinionPro.*", "SimSun");
        addSimilarFontReplaceRegexMapping(".*SimSun.*", "SimSun");
        addSimilarFontReplaceRegexMapping(".*Song.*", "宋体");
        addSimilarFontReplaceRegexMapping(".*MinionPro.*", "SimSun");

        /*
         * 默认字体 选择
         *
         * 默认选择宋体 或 衬体
         */
        String[] arr = new String[]{
                "宋体", "楷体", "仿宋"
        };
        String defFt = null;
        for (String name : arr) {
            defFt = getReplaceSimilarFontPath(name, "");
            if (loadAsDefaultFont(defFt)) {
                break;
            } else {
                defFt = null;
            }
        }

在 FontLoader.getInstance()这里的时候已经使用到了字体，就已经抛异常了。我这边是干预不到的。你看看能不能init时候增加参数让我们可以自定义别名来使用。

**Comment by lubiaook** [comment]
楼主问题解决了吗？
