### ISSUE TITLE
ofd转pdf使用PDFBox 包转换报错

### ISSUE THREAD

**Issue by ggxinyan** [ofdrw/ofdrw#206]
版本ofdrw-converter.2.0.2.jar（之前之后的版本都做过测试，基本一样的报错）
是iText转PDF格式差异较大，且会变成黑色。使用PDFBox 转换报错。望解惑
报错内容：
org.ofdrw.converter.GeneralConvertException: java.lang.ClassCastException: org.ofdrw.core.pageDescription.color.pattern.CT_Pattern cannot be cast to org.ofdrw.core.pageDescription.color.color.CT_AxialShd
	at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:132)
	at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:215)
	at com.haizhi.metis.document.parse.transformation.utils.OFDUtil.ofdToPdf(OFDUtil.java:32)
	at com.haizhi.metis.document.parse.transformation.utils.OFDUtil.main(OFDUtil.java:57)
Caused by: java.lang.ClassCastException: org.ofdrw.core.pageDescription.color.pattern.CT_Pattern cannot be cast to org.ofdrw.core.pageDescription.color.color.CT_AxialShd
	at org.ofdrw.converter.PdfboxMaker.setShadingFill(PdfboxMaker.java:395)
	at org.ofdrw.converter.PdfboxMaker.writePath(PdfboxMaker.java:383)
	at org.ofdrw.converter.PdfboxMaker.writePageBlock(PdfboxMaker.java:284)
	at org.ofdrw.converter.PdfboxMaker.writeAnnoAppearance(PdfboxMaker.java:223)
	at org.ofdrw.converter.PdfboxMaker.makePage(PdfboxMaker.java:126)
	at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:102)
	... 3 more

**Comment by Trisia** [comment]
颜色值问题已经在 2.0.10 跳过
