### ISSUE TITLE
Linux 环境下 FontLoader.getInstance() 初始化失败

### ISSUE THREAD

**Issue by Wang-Kowah** [ofdrw/ofdrw#213]
**版本：2.0.10**
尝试ofd转pdf时出现如下报错，无法干预，请问有什么办法可以兼容。

statck_trace：
```
java.lang.NullPointerException: null
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.ofdrw.converter.FontLoader.loadAsDefaultFont(FontLoader.java:219)
	at org.ofdrw.converter.FontLoader.init(FontLoader.java:189)
	at org.ofdrw.converter.FontLoader.syncInit(FontLoader.java:91)
	at org.ofdrw.converter.FontLoader.getInstance(FontLoader.java:132)
```
系统中的中文字体：
```
$ fc-list :lang=zh
/usr/share/fonts/cjkuni-ukai/ukai.ttc: AR PL UKai TW:style=Book
/usr/share/fonts/cjkuni-ukai/ukai.ttc: AR PL UKai HK:style=Book
/usr/share/fonts/cjkuni-ukai/ukai.ttc: AR PL UKai CN:style=Book
/usr/share/fonts/cjkuni-uming/uming.ttc: AR PL UMing TW MBE:style=Light
/usr/share/fonts/cjkuni-ukai/ukai.ttc: AR PL UKai TW MBE:style=Book
/usr/share/fonts/cjkuni-uming/uming.ttc: AR PL UMing TW:style=Light
/usr/share/fonts/cjkuni-uming/uming.ttc: AR PL UMing HK:style=Light
/usr/share/fonts/cjkuni-uming/uming.ttc: AR PL UMing CN:style=Light
```

**Comment by aaafenghao** [comment]
我也遇到相同问题，有解决方案么

**Comment by Wang-Kowah** [comment]
> 我也遇到相同问题，有解决方案么

我回退到内嵌字体文件的 2.0.3 版本了，不使用系统字体

**Comment by Trisia** [comment]
将windows字体目录下的所有字体复制服务器上相应位置。
