### ISSUE TITLE
导出为图片时字体缺失 Cannot invoke "org.ofdrw.converter.font.TrueTypeFont.getUnicodeGlyph(int)" because "typeFont" is null

### ISSUE THREAD

**Issue by zhangyw** [ofdrw/ofdrw#214]
17:37:21.336 [main] INFO org.ofdrw.converter.ImageMaker -- 无法加载字体ID：9
17:37:21.336 [main] WARN org.ofdrw.converter.ImageMaker -- PageBlock无法渲染:
java.lang.NullPointerException: Cannot invoke "org.ofdrw.converter.font.TrueTypeFont.getUnicodeGlyph(int)" because "typeFont" is null
	at org.ofdrw.converter.AWTMaker.writeText(AWTMaker.java:463)
	at org.ofdrw.converter.AWTMaker.writeContent(AWTMaker.java:261)
	at org.ofdrw.converter.AWTMaker.writeContent(AWTMaker.java:273)
	at org.ofdrw.converter.AWTMaker.writeContent(AWTMaker.java:273)
	at org.ofdrw.converter.AWTMaker.writePage(AWTMaker.java:208)
	at org.ofdrw.converter.ImageMaker.makePage(ImageMaker.java:68)
	at org.ofdrw.converter.export.ImageExporter.export(ImageExporter.java:158)

**Comment by zhangyw** [comment]
测试文件：999.ofd, 运行环境，mac os。 另外ubuntu上也同样会丢失文件中的中文

**Comment by crg1433** [comment]
回退到2.0.3版本，2.0.3自带字体

**Comment by Trisia** [comment]
字体问题，请在操作系统内安装中宋体、黑体等字体。
