### ISSUE TITLE
convert to pdf failed with error ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by windowye** [ofdrw/ofdrw#215]
### error log

```
18:01:27.053 [main] ERROR org.ofdrw.converter.ConvertHelper - convert to pdf failed
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ofdrw.converter.ItextMaker.writePath(ItextMaker.java:427) ~[classes/:?]
	at org.ofdrw.converter.ItextMaker.writePageBlock(ItextMaker.java:324) ~[classes/:?]
	at org.ofdrw.converter.ItextMaker.writeLayer(ItextMaker.java:217) ~[classes/:?]
	at org.ofdrw.converter.ItextMaker.makePage(ItextMaker.java:121) ~[classes/:?]
	at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:87) [classes/:?]
	at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:215) [classes/:?]
	at HelloWorld.main(HelloWorld.java:41) [test-classes/:?]
org.ofdrw.converter.GeneralConvertException: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:132)
	at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:215)
	at HelloWorld.main(HelloWorld.java:41)
```

file download link

https://cowtransfer.com/s/4f33c254cf6c4e 点击链接查看 [ 测试表单.ofd ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 mfxxsg 查看；

**Comment by Trisia** [comment]
已经兼容
