### ISSUE TITLE
向OFD中添加附件失败

### ISSUE THREAD

**Issue by zhangzhen1979** [ofdrw/ofdrw#250]
执行官方的测试代码，如下：
```
   /**
     * 向文件中加入附件文件
     */
    @Test
    void addAttachmentTest() throws IOException {
        Path outP = Paths.get("target/AddAttachment.ofd");
        Path file = Paths.get("src/test/resources", "eg_tulip.jpg");
        Path file2 = Paths.get("src/test/resources", "NotoSerifCJKsc-Regular.otf");

        try (OFDDoc ofdDoc = new OFDDoc(outP)) {
            Paragraph p = new Paragraph();
            Span span = new Span("这是一个带有附件的OFD文件").setFontSize(10d);
            p.add(span);
            ofdDoc.add(p);

            // 加入附件文件
            ofdDoc.addAttachment(new Attachment("Gao", file));
            ofdDoc.addAttachment(new Attachment("FontFile", file2));
        }
        System.out.println("生成文档位置：" + outP.toAbsolutePath().toString());
    }
```

报错信息如下：

```
Exception in thread "main" java.io.FileNotFoundException: 容器内无法找名为：Res目录
	at org.ofdrw.pkg.container.VirtualContainer.getContainer(VirtualContainer.java:376)
	at org.ofdrw.pkg.container.DocDir.getRes(DocDir.java:229)
	at org.ofdrw.layout.OFDDoc.addAttachment(OFDDoc.java:452)
	at com.thinkdifferent.convertpreview.T1.main(T1.java:31)
```

**Comment by zhangzhen1979** [comment]
加入附件代码改为如下内容，即可：
```
            // 加入附件文件
            ofdDoc.addAttachment("/Attachments",new Attachment("Gao", file));
```

**Comment by Trisia** [comment]
fixed in 2.2.11
