### ISSUE TITLE
ofd 转 html 后盖章和二维码图片丢失问题

### ISSUE THREAD

**Issue by chang-shuai** [ofdrw/ofdrw#329]
**用的不是 SpringBoot fatjar 包**

通过 HTMLExporter 将 ofd 转为 html 时报错，无法获取图片

```
2024-12-13 09:15:47.277  WARN 26018 --- [  XNIO-2 task-2] org.ofdrw.converter.SVGMaker : PageBlock无法渲染:

java.lang.NullPointerException: null
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.encodeImage(ImageHandlerBase64Encoder.java:157)
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.handleHREF(ImageHandlerBase64Encoder.java:133)
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.handleHREF(ImageHandlerBase64Encoder.java:72)
	at org.apache.batik.svggen.DefaultImageHandler.handleImage(DefaultImageHandler.java:63)
	at org.apache.batik.svggen.SimpleImageHandler.handleImage(SimpleImageHandler.java:100)
	at org.apache.batik.svggen.SVGGraphics2D.drawImage(SVGGraphics2D.java:677)
	at org.apache.batik.svggen.SVGGraphics2D.drawImage(SVGGraphics2D.java:868)
	at org.ofdrw.converter.AWTMaker.writeImage(AWTMaker.java:413)
	at org.ofdrw.converter.AWTMaker.writeContent(AWTMaker.java:274)
	at org.ofdrw.converter.AWTMaker.writePage(AWTMaker.java:234)
	at org.ofdrw.converter.SVGMaker.makePage(SVGMaker.java:79)
	at org.ofdrw.converter.HtmlMaker.makePageDiv(HtmlMaker.java:257)
	at org.ofdrw.converter.export.HTMLExporter.export(HTMLExporter.java:186)
	at com.lone.scc.common.provider.OfdSwitchPdfProvider.switchPdf(OfdSwitchPdfProvider.java:49)
	at com.lone.scc.common.provider.OfdSwitchPdfProvider$$FastClassBySpringCGLIB$$ba3fbebe.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.lone.scc.common.provider.OfdSwitchPdfProvider$$EnhancerBySpringCGLIB$$478b0697.switchPdf(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

![image](https://github.com/user-attachments/assets/7cf4cafc-2f3a-4187-b889-2e37608b9fb5)

定位原因后，发现 `ofdrw-converter` 存在 `org.apache.batik.ext.awt.image.spi.ImageWriterRegistry`  类 用于覆盖了 `batik-awt-util` 中的  `org.apache.batik.ext.awt.image.spi.ImageWriterRegistry`  类。

`batik-awt-util`  中的 `ImageWriterRegistry#setup` 代码如下：

```java
    private void setup() {
        Iterator iter = Service.providers(ImageWriter.class);
        while (iter.hasNext()) {
            ImageWriter writer = (ImageWriter)iter.next();
            // System.out.println("RE: " + writer);
            register(writer);
        }
    }
```

`ofdrw-converter` 中的 `ImageWriterRegistry#setup` 代码如下：

```java
    private void setup() {
        Iterator iter = Service.providers(org.apache.xmlgraphics.image.writer.ImageWriter.class);
        while (iter.hasNext()) {
            ImageWriter writer = (ImageWriter)iter.next();
            // System.out.println("RE: " + writer);
            register(writer);
        }
    }
```

通过查看 jar 包里的 `MANIFEST.MF` 文件中的 `Class-Path` ，发现 `batik-awt-util` 比 `ofdrw-converter` 加载的更早。所以 `org.apache.batik.ext.awt.image.spi.ImageWriterRegistry`  类还是使用  `batik-awt-util` 包中的。

![image](https://github.com/user-attachments/assets/d6fd59eb-5bab-468a-aa5d-606c84d542d7)

![image](https://github.com/user-attachments/assets/1affb4c9-ed9f-4a28-838f-1fdbafd4d36d)

**临时解决办法**

修改 `pom.xml` 文件，打包时，将 `MANIFEST.MF` 文件中的 `Class-Path` 中的  `ofdrw-converter`  放到前面。

**Comment by Trisia** [comment]
是包冲突了吗？

**Comment by Trisia** [comment]
超时关闭
